    services:
      - type: web
        name: productivity-tips-api
        env: node
        plan: free
        repo: https://github.com/HinnHabib/angular-remix
        branch: main
        buildCommand: yarn install && yarn build
        startCommand: yarn start
        

    